### ISSUE TITLE
NPM package

### ISSUE THREAD

**Issue by anthonyvialleton** [pimbrouwers/YUI-Pure-CSS-Extensions#6]
Hello guys, 

Could you make a npm package to be able to import it correctly ?

Thanks a lot !

**Comment by pimbrouwers** [comment]
Hi Anthony,

Thanks for reaching out.

I haven't paid much attention to this repository in quite some time since Pure wasn't being actively maintained anymore. Instead, I've been focusing most of my attention on my own css framework [Hydrogen](https://github.com/pimbrouwers/hydrogen).

I have no problem obliging to this request, and will do so at my earliest convenience in the next few weeks.

Thanks for your support.

**Comment by pimbrouwers** [comment]
@anthonyvialleton Thanks so much for your patience and patronage. I've added full 24th and 5th support to the push-pull and flex-grid and converted the project to a pure npm solution.

You can find officially use this as an npm package by running:

`npm i purecss-utils`
